    - name: copy catalogue service file
      ansible.builtin.template:
        src: catalogue.service.j2
        dest: /etc/systemd/system/catalogue.service
        mode: '0644'

    - name: Reload systemd to recognize new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes
    
    - name: Ensure catalogue service is running
      ansible.builtin.command: systemctl status catalogue
      register: catalogue_status
      failed_when: "'Active: active (running)' not in catalogue_status.stdout"
      changed_when: false
